### ISSUE TITLE
Installation issues with Python 3.6

### ISSUE THREAD

**Issue by jonnor** [Kota-Dohi/dcase2022_task2_baseline_ae#1]
The README says to use Python 3.6.x. But when I tried this version many dependencies could not be installed at the version specified in the requirements.txt. I tried Python 3.8 instead, and that works.

Maybe update the documentation to say Python 3.8 instead of 3.6 ?

I believe the same may be the case for the other baseline repository.

**Comment by Kota-Dohi** [comment]
Thank you for the notice. We're using Python 3.8.12 this year, but we forgot to update the README. We apologize for the inconvenience.

**Comment by jonnor** [comment]
No problem. Thanks for the quick fix!
