### ISSUE TITLE
logical problems

### ISSUE THREAD

**Issue by KAI-LI-JAIST** [Kota-Dohi/dcase2022_task2_baseline_ae#2]
Hi!
Thank you so much for your code.
I have a simple question about this system.

This is a binary classification mission.
Why the model input and output are the same? (regression mission?)

Looking forward to receive your reply!

**Comment by Kota-Dohi** [comment]
Hi, thank you for your question!

This is an unsupervised anomaly detection task, and we can only use normal samples for training.
Therefore, we cannot train models that just classify normal samples and anomalous samples.

Instead, we use an autoencoder and calculate anomaly scores by the reconstruction error between 
input and reconstructed output. This is why the model input and output have the same dimensions.

**Comment by KAI-LI-JAIST** [comment]
I got it. 
Thank you so much for your explanation!
